# Import, recode, and score ----------------------------------------------------

if (!file.exists(DATA_FILE)) {
  stop("Data file not found at project root: ", DATA_FILE)
}

# Start a fresh audit log for each pipeline run.
audit_path <- file.path(LOG_DIR, "transformation_audit_log.csv")
if (file.exists(audit_path)) file.remove(audit_path)

raw_data <- readxl::read_excel(DATA_FILE, sheet = DATA_SHEET, .name_repair = "unique")
raw_data <- raw_data |> dplyr::rename_with(~ stringr::str_trim(.x))
append_audit_log("import", DATA_FILE, paste0("Imported sheet ", DATA_SHEET), nrow(raw_data), ncol(raw_data))

# Harmonize age naming found in the data dictionary versus the data frame.
if ("age" %in% names(raw_data) && !"age_years" %in% names(raw_data)) {
  raw_data <- raw_data |> dplyr::rename(age_years = age)
  append_audit_log("rename", "age", "Renamed age to age_years", columns_affected = 1)
}

# Resolve duplicated ac_total columns generated by readxl name repair.
ac_candidates <- grep("^ac_total(\\.\\.\\.[0-9]+|\\.[0-9]+)?$", names(raw_data), value = TRUE)
if (length(ac_candidates) > 1) {
  nonempty_counts <- vapply(raw_data[ac_candidates], function(x) sum(!is.na(x)), numeric(1))
  keep_ac <- ac_candidates[which.max(nonempty_counts)]
  drop_ac <- setdiff(ac_candidates, keep_ac)
  raw_data <- raw_data |>
    dplyr::rename(ac_total = dplyr::all_of(keep_ac)) |>
    dplyr::select(-dplyr::all_of(drop_ac))
  append_audit_log(
    "duplicate-column resolution", "ac_total",
    paste0("Kept ", keep_ac, "; removed ", paste(drop_ac, collapse = ", ")),
    columns_affected = length(drop_ac)
  )
} else if (length(ac_candidates) == 1 && ac_candidates != "ac_total") {
  old_name <- ac_candidates
  raw_data <- raw_data |> dplyr::rename(ac_total = dplyr::all_of(old_name))
  append_audit_log("rename", old_name, "Standardized duplicate-repaired name to ac_total", columns_affected = 1)
}

# Remove columns that are entirely missing.
empty_columns <- names(raw_data)[vapply(raw_data, function(x) all(is.na(x)), logical(1))]
if (length(empty_columns) > 0) {
  raw_data <- raw_data |> dplyr::select(-dplyr::all_of(empty_columns))
  append_audit_log(
    "remove columns", "all-missing columns",
    paste(empty_columns, collapse = ", "), columns_affected = length(empty_columns)
  )
}

# Reconstruct raw wording variables when only reverse-scored versions exist.
reverse_pairs <- c(
  competence_ET_2_r = "competence_ET_2_raw",
  competence_US_3_r = "competence_US_3_raw",
  competence_AW_8_r = "competence_AW_8_raw"
)
for (scored_name in names(reverse_pairs)) {
  raw_name <- unname(reverse_pairs[[scored_name]])
  if (scored_name %in% names(raw_data) && !raw_name %in% names(raw_data)) {
    raw_data[[raw_name]] <- reverse_1_to_5(raw_data[[scored_name]])
    append_audit_log("reverse-score reconstruction", raw_name,
                     paste0("Created from already-scored ", scored_name, " using 6 - x"),
                     rows_affected = sum(!is.na(raw_data[[scored_name]])), columns_affected = 1)
  }
}

# If unscored source variables are supplied in a future dataset, create _r versions.
forward_pairs <- c(
  competence_ET_2 = "competence_ET_2_r",
  competence_US_3 = "competence_US_3_r",
  competence_AW_8 = "competence_AW_8_r"
)
for (raw_name in names(forward_pairs)) {
  scored_name <- unname(forward_pairs[[raw_name]])
  if (raw_name %in% names(raw_data) && !scored_name %in% names(raw_data)) {
    raw_data[[scored_name]] <- reverse_1_to_5(raw_data[[raw_name]])
    append_audit_log("reverse scoring", scored_name,
                     paste0("Created from ", raw_name, " using 6 - x"),
                     rows_affected = sum(!is.na(raw_data[[raw_name]])), columns_affected = 1)
  }
}

check_required_columns(raw_data, c(ATT_POS_ITEMS, ATT_NEG_ITEMS, COMP_ALL_ITEMS), "scale scoring")

# Validate the expected 1-5 item range and convert out-of-range values to NA.
scale_source_items <- unique(c(ATT_POS_ITEMS, ATT_NEG_ITEMS, COMP_ALL_ITEMS, "ac_1", "ac_2", "ac_3", "ac_4"))
scale_source_items <- intersect(scale_source_items, names(raw_data))
invalid_value_log <- purrr::map_dfr(scale_source_items, function(v) {
  x <- suppressWarnings(as.numeric(raw_data[[v]]))
  invalid <- !is.na(x) & !(x %in% 1:5)
  if (any(invalid)) raw_data[[v]][invalid] <<- NA
  tibble::tibble(variable = v, invalid_values_set_to_na = sum(invalid))
})
if (sum(invalid_value_log$invalid_values_set_to_na) > 0) {
  append_audit_log("invalid-value recoding", "Likert items",
                   "Values outside 1-5 were converted to NA",
                   rows_affected = sum(invalid_value_log$invalid_values_set_to_na))
}

# Missingness before row filtering.
missingness_before <- missingness_summary(raw_data)
write_workbook_safely(
  list(Missingness_before = missingness_before, Invalid_values = invalid_value_log),
  file.path(TABLE_DIR, "data_quality_before_filtering.xlsx")
)

# Recoded labels for descriptive output. Numeric source variables remain unchanged.
data_labeled <- raw_data |>
  dplyr::mutate(
    consent_label = factor(consent, levels = c(0, 1), labels = c("No", "Yes")),
    gender_label = factor(gender, levels = c(0, 1, 2, 3),
                          labels = c("Prefer not to answer", "Woman", "Man", "Non-binary")),
    occupation_label = factor(occupation, levels = 0:4,
      labels = c("Other", "University student", "University professor",
                 "Technician or technologist", "Healthcare professional")),
    study_work_area_label = factor(study_work_area, levels = 0:8,
      labels = c("Other", "Psychology", "Nursing", "Medicine",
                 "Other healthcare professions", "Education", "Engineering",
                 "Law, social sciences & humanities", "Business & commerce")),
    commitment_label = factor(commitment, levels = 0:2,
      labels = c("No, I do not commit", "Yes, I commit", "I cannot make that commitment")),
    across(dplyr::all_of(BINARY_TECH_VARS), ~ factor(.x, levels = c(0, 1), labels = c("No", "Yes")),
           .names = "{.col}_label")
  )
append_audit_log("label creation", "categorical variables",
                 "Created English-language factor labels without replacing numeric source columns")

# Core analysis inclusion: consent, commitment, and attention-check criteria.
row_audit <- raw_data |>
  dplyr::mutate(
    source_row = dplyr::row_number(),
    consent_ok = if (REQUIRE_CONSENT) !is.na(consent) & consent == 1 else TRUE,
    commitment_ok = if (REQUIRE_COMMITMENT) !is.na(commitment) & commitment == 1 else TRUE,
    attention_ok = if ("ac_total" %in% names(raw_data)) !is.na(ac_total) & ac_total >= MIN_ATTENTION_TOTAL else TRUE,
    core_analysis_included = consent_ok & commitment_ok & attention_ok,
    exclusion_reason = dplyr::case_when(
      !consent_ok ~ "Consent criterion not met or missing",
      !commitment_ok ~ "Commitment criterion not met or missing",
      !attention_ok ~ "Attention-check criterion not met or missing",
      TRUE ~ "Included"
    )
  )

analysis_data <- raw_data[row_audit$core_analysis_included, , drop = FALSE]
append_audit_log("row filtering", "core analysis sample",
                 paste0("Applied consent, commitment, and attention criteria; retained ", nrow(analysis_data),
                        " of ", nrow(raw_data), " rows"),
                 rows_affected = sum(!row_audit$core_analysis_included))

# Create reverse-scored GAAIS negative items and scale scores.
analysis_data <- analysis_data |>
  dplyr::mutate(
    across(dplyr::all_of(ATT_NEG_ITEMS), reverse_1_to_5, .names = "{.col}_r")
  )
append_audit_log("reverse scoring", "GAAIS negative items",
                 paste0("Created ", paste0(ATT_NEG_ITEMS, "_r", collapse = ", "), " using 6 - x"),
                 rows_affected = nrow(analysis_data), columns_affected = length(ATT_NEG_ITEMS))

attitude_items_scored <- c(ATT_POS_ITEMS, paste0(ATT_NEG_ITEMS, "_r"))
analysis_data <- analysis_data |>
  dplyr::mutate(
    attitude_valid_prop = rowMeans(!is.na(dplyr::pick(dplyr::all_of(attitude_items_scored)))),
    competence_valid_prop = rowMeans(!is.na(dplyr::pick(dplyr::all_of(COMP_ALL_ITEMS)))),
    attitude_scale_eligible = attitude_valid_prop >= MIN_VALID_ITEM_PROP,
    competence_scale_eligible = competence_valid_prop >= MIN_VALID_ITEM_PROP,
    attitude_positive = dplyr::if_else(
      attitude_scale_eligible,
      rowMeans(dplyr::pick(dplyr::all_of(ATT_POS_ITEMS)), na.rm = TRUE), NA_real_
    ),
    attitude_negative_favorable = dplyr::if_else(
      attitude_scale_eligible,
      rowMeans(dplyr::pick(dplyr::all_of(paste0(ATT_NEG_ITEMS, "_r"))), na.rm = TRUE), NA_real_
    ),
    attitude_favorability_index = dplyr::if_else(
      attitude_scale_eligible,
      rowMeans(dplyr::pick(dplyr::all_of(attitude_items_scored)), na.rm = TRUE), NA_real_
    ),
    competence_awareness = dplyr::if_else(
      competence_scale_eligible, rowMeans(dplyr::pick(dplyr::all_of(COMP_AWARENESS)), na.rm = TRUE), NA_real_),
    competence_usage = dplyr::if_else(
      competence_scale_eligible, rowMeans(dplyr::pick(dplyr::all_of(COMP_USAGE)), na.rm = TRUE), NA_real_),
    competence_evaluation = dplyr::if_else(
      competence_scale_eligible, rowMeans(dplyr::pick(dplyr::all_of(COMP_EVALUATION)), na.rm = TRUE), NA_real_),
    competence_ethics = dplyr::if_else(
      competence_scale_eligible, rowMeans(dplyr::pick(dplyr::all_of(COMP_ETHICS)), na.rm = TRUE), NA_real_),
    competence_total = dplyr::if_else(
      competence_scale_eligible, rowMeans(dplyr::pick(dplyr::all_of(COMP_ALL_ITEMS)), na.rm = TRUE), NA_real_)
  )
append_audit_log("scale scoring", "attitudes and competence",
                 paste0("Row means computed only when at least ", MIN_VALID_ITEM_PROP * 100,
                        "% of scale items were valid"), rows_affected = nrow(analysis_data))

scale_missingness_decision <- tibble::tibble(
  scale = c("GAAIS attitudes", "AI competence"),
  items = c(length(attitude_items_scored), length(COMP_ALL_ITEMS)),
  minimum_valid_proportion = MIN_VALID_ITEM_PROP,
  eligible_rows = c(sum(analysis_data$attitude_scale_eligible), sum(analysis_data$competence_scale_eligible)),
  ineligible_rows = c(sum(!analysis_data$attitude_scale_eligible), sum(!analysis_data$competence_scale_eligible)),
  complete_case_rows = c(
    sum(stats::complete.cases(analysis_data[, attitude_items_scored])),
    sum(stats::complete.cases(analysis_data[, COMP_ALL_ITEMS]))
  ),
  decision = c(
    "Do not delete rows globally; exclude only from attitude analyses when below threshold.",
    "Do not delete rows globally; exclude only from competence analyses when below threshold."
  )
)

sample_flow <- tibble::tibble(
  stage = c("Imported", "Core criteria passed", "Attitude-scale eligible", "Competence-scale eligible",
            "Eligible for both scales"),
  rule = c(
    "All rows in source file",
    "Consent, commitment, and attention criteria",
    paste0("At least ", MIN_VALID_ITEM_PROP * 100, "% of attitude items valid"),
    paste0("At least ", MIN_VALID_ITEM_PROP * 100, "% of competence items valid"),
    "Eligible for both attitude and competence scores"
  ),
  n = c(
    nrow(raw_data), nrow(analysis_data),
    sum(analysis_data$attitude_scale_eligible),
    sum(analysis_data$competence_scale_eligible),
    sum(analysis_data$attitude_scale_eligible & analysis_data$competence_scale_eligible)
  )
)

missingness_after <- missingness_summary(analysis_data)
write_workbook_safely(
  list(
    Sample_flow = sample_flow,
    Row_exclusion_log = row_audit,
    Scale_missingness_decision = scale_missingness_decision,
    Missingness_after = missingness_after
  ),
  file.path(TABLE_DIR, "sample_and_missingness_audit.xlsx")
)

saveRDS(analysis_data, file.path(OUTPUT_DIR, "analysis_data_scored.rds"))
openxlsx::write.xlsx(analysis_data, file.path(OUTPUT_DIR, "analysis_data_scored.xlsx"), overwrite = TRUE)